# Generated by Django 4.1.5 on 2023-10-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inv", "0005_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="existencia",
            field=models.FloatField(default=0),
        ),
    ]
